---
govc_env: &govc_env
  GOVC_INSECURE: "true"
  GOVC_URL: https://((vsphere.server))/sdk
  GOVC_USERNAME: ((vsphere.user))
  GOVC_PASSWORD: ((vsphere.password))
  GOVC_DATACENTER: Datacenter
  GOVC_DATASTORE: Datastore 1
  GOVC_NETWORK: VM Network
  GOVC_RESOURCE_POOL: ClusterAPI
  DEBUG: "false"

s3_env: &s3_env
  bucket: concourse
  endpoint: ((s3.endpoint))
  access_key_id: ((s3.access_key))
  secret_access_key: ((s3.secret_key))

vsphere_env: &vsphere_env
  VSPHERE_USERNAME: ((vsphere.user))
  VSPHERE_PASSWORD: ((vsphere.password))
  VSPHERE_DATACENTER: Datacenter
  VSPHERE_DATASTORE: Datastore 1
  VSPHERE_NETWORK: VM Network
  VSPHERE_SERVER: ((vsphere.server))
  VSPHERE_SSH_AUTHORIZED_KEY: ((ssh_authorized_key))
  VSPHERE_RESOURCE_POOL: ClusterAPI
  VSPHERE_FOLDER: ClusterAPI
  EXP_CLUSTER_RESOURCE_SET: "true"

resources:
  - name: pipelines
    type: git
    source:
      uri: git@github.com:spiegela/spieg-pipelines.git
      branch: master
      private_key: ((private_key))

  - name: kube-template-v1.17.x
    type: s3
    source:
      regexp: ClusterAPI/assets/capv/kube/ubuntu-1804-kube-v(1.17.5).ova
      <<: *s3_env

  - name: kube-template-v1.18.x
    type: s3
    source:
      regexp: ClusterAPI/assets/capv/kube/ubuntu-1804-kube-v(1.18.2).ova
      <<: *s3_env

  - name: kube-template-info-v1.17.x
    type: s3
    source:
      versioned_file: ClusterAPI/assets/capv/kube/capv-template-info-v1.17.x.json
      <<: *s3_env

  - name: kube-template-info-v1.18.x
    type: s3
    source:
      versioned_file: ClusterAPI/assets/capv/kube/capv-template-info-v1.18.x.json
      <<: *s3_env

  - name: microk8s-config
    type: s3
    source:
      versioned_file: ClusterAPI/microk8s/config
      <<: *s3_env

  - name: microk8s-info
    type: s3
    source:
      versioned_file: ClusterAPI/microk8s/microk8s-info.json
      <<: *s3_env

  - name: microk8s-ip-address
    type: s3
    source:
      versioned_file: ClusterAPI/microk8s/ip-address
      <<: *s3_env

  - name: clusterctl-release
    type: github-release
    source:
      access_token: ((git_token))
      owner: kubernetes-sigs
      repository: cluster-api
      private_key: ((private_key))

  - name: gamboge-cluster-yaml
    type: s3
    source:
      versioned_file: ClusterAPI/gamboge/cluster.yaml
      <<: *s3_env

  - name: jonquil-cluster-yaml
    type: s3
    source:
      versioned_file: ClusterAPI/jonquil/cluster.yaml
      <<: *s3_env

  - name: gamboge-kubeconfig
    type: s3
    source:
      versioned_file: ClusterAPI/gamboge/kubeconfig
      <<: *s3_env

  - name: jonquil-kubeconfig
    type: s3
    source:
      versioned_file: ClusterAPI/jonquil/kubeconfig
      <<: *s3_env

jobs:

  - name: kube-templates-1.17.x
    plan:
      - in_parallel:
          - get: pipelines
          - get: kube-template-v1.17.x
            trigger: true
      - task: check-previous
        file: pipelines/tasks/skip-unless-vm-exists/task.yml
        output_mapping:
          output: delete-conditions
        params:
          <<: *govc_env
          VM: /Datacenter/vm/ClusterAPI/ubuntu-1804-kube-v1.17.5
      - task: delete-previous
        file: pipelines/tasks/govc-cmd/task.yml
        input_mapping:
          conditions: delete-conditions
        params:
          <<: *govc_env
          COMMAND: vm.destroy
          ARGS: ubuntu-1804-kube-v1.17.5
      - task: import-ova-spec
        file: pipelines/tasks/govc-cmd/task.yml
        input_mapping:
          files: kube-template-v1.17.x
        output_mapping:
          output: ova-spec
        params:
          <<: *govc_env
          COMMAND: import.spec
          ARGS: files/ubuntu-1804-kube-v1.17.5.ova
      - task: configure-ova-network
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cincan/jq
              tag: latest
          inputs:
            - name: ova-spec
          outputs:
            - name: configured-ova-spec
          run:
            path: /bin/ash
            args:
              - -c
              - |
                if [[ $DEBUG == "true" ]]; then
                  set -x
                fi
                jq '.NetworkMapping[].Network = "VM Network"' < ova-spec/govc-cmd.out > configured-ova-spec/spec.json
      - task: import-ova
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalgreenhouse/govc
              tag: latest
          inputs:
            - name: configured-ova-spec
            - name: kube-template-v1.17.x
          params:
            <<: *govc_env
          run:
            path: /bin/bash
            args:
              - -c
              - |
                if [[ $DEBUG == true ]]; then
                  set -x
                fi
                govc import.ova -folder=ClusterAPI --options=configured-ova-spec/spec.json kube-template-v1.17.x/ubuntu-1804-kube-v1.17.5.ova
      - task: templatize
        file: pipelines/tasks/govc-cmd/task.yml
        params:
          <<: *govc_env
          COMMAND: vm.markastemplate
          ARGS: ubuntu-1804-kube-v1.17.5
      - task: get-info
        file: pipelines/tasks/govc-cmd/task.yml
        output_mapping:
          output: vm-info
        params:
          <<: *govc_env
          COMMAND: vm.info
          ARGS: -json -r /Datacenter/vm/ClusterAPI/ubuntu-1804-kube-v1.17.5
      - put: kube-template-info-v1.17.x
        params:
          file: vm-info/govc-cmd.out

  - name: kube-templates-1.18.x
    plan:
      - in_parallel:
          - get: pipelines
          - get: kube-template-v1.18.x
            trigger: true
      - task: check-previous
        file: pipelines/tasks/skip-unless-vm-exists/task.yml
        output_mapping:
          output: delete-conditions
        params:
          <<: *govc_env
          VM: /Datacenter/vm/ClusterAPI/ubuntu-1804-kube-v1.18.2
      - task: delete-previous
        file: pipelines/tasks/govc-cmd/task.yml
        input_mapping:
          conditions: delete-conditions
        params:
          <<: *govc_env
          COMMAND: vm.destroy
          ARGS: ubuntu-1804-kube-v1.18.2
      - task: import-ova-spec
        file: pipelines/tasks/govc-cmd/task.yml
        input_mapping:
          files: kube-template-v1.18.x
        output_mapping:
          output: ova-spec
        params:
          <<: *govc_env
          COMMAND: import.spec
          ARGS: files/ubuntu-1804-kube-v1.18.2.ova
      - task: configure-ova-network
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cincan/jq
              tag: latest
          inputs:
            - name: ova-spec
          outputs:
            - name: configured-ova-spec
          run:
            path: /bin/ash
            args:
              - -c
              - |
                if [[ $DEBUG == "true" ]]; then
                  set -x
                fi
                jq '.NetworkMapping[].Network = "VM Network"' < ova-spec/govc-cmd.out > configured-ova-spec/spec.json
      - task: import-ova
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalgreenhouse/govc
              tag: latest
          inputs:
            - name: configured-ova-spec
            - name: kube-template-v1.18.x
          params:
            <<: *govc_env
          run:
            path: /bin/bash
            args:
              - -c
              - |
                if [[ $DEBUG == true ]]; then
                  set -x
                fi
                govc import.ova -folder=ClusterAPI --options=configured-ova-spec/spec.json kube-template-v1.18.x/ubuntu-1804-kube-v1.18.2.ova
      - task: templatize
        file: pipelines/tasks/govc-cmd/task.yml
        params:
          <<: *govc_env
          COMMAND: vm.markastemplate
          ARGS: ubuntu-1804-kube-v1.18.2
      - task: get-info
        file: pipelines/tasks/govc-cmd/task.yml
        output_mapping:
          output: vm-info
        params:
          <<: *govc_env
          COMMAND: vm.info
          ARGS: -json -r /Datacenter/vm/ClusterAPI/ubuntu-1804-kube-v1.18.2
      - put: kube-template-info-v1.18.x
        params:
          file: vm-info/govc-cmd.out

  - name: microk8s-vm
    plan:
      - get: pipelines
      - task: check-previous
        file: pipelines/tasks/skip-unless-vm-exists/task.yml
        output_mapping:
          output: delete-conditions
        params:
          <<: *govc_env
          VM: /Datacenter/vm/ClusterAPI/microk8s
      - task: delete-previous
        file: pipelines/tasks/govc-cmd/task.yml
        input_mapping:
          conditions: delete-conditions
        params:
          <<: *govc_env
          COMMAND: vm.destroy
          ARGS: microk8s
      - task: clone-from-template
        file: pipelines/tasks/govc-cmd/task.yml
        params:
          <<: *govc_env
          COMMAND: vm.clone
          ARGS: -on=true -vm ClusterAPI/microk8s-template -folder ClusterAPI microk8s
      - task: wait-for-address
        file: pipelines/tasks/wait-for-vm-address/task.yml
        output_mapping:
          output: vm-info
        params:
          <<: *govc_env
          VM: /Datacenter/vm/ClusterAPI/microk8s
      - put: microk8s-info
        params:
          file: vm-info/vm-info.json
      - put: microk8s-ip-address
        params:
          file: vm-info/ip-address

  - name: microk8s-config
    plan:
      - in_parallel:
          - get: pipelines
          - get: microk8s-ip-address
            passed:
              - microk8s-vm
      - task: get-microk8s-config
        file: pipelines/tasks/ssh-exec/task.yml
        input_mapping:
          connection: microk8s-ip-address
        output_mapping:
          output: microk8s-config
        params:
          PRIVATE_KEY: ((private_key))
          USERNAME: spiegela
          COMMAND: /snap/bin/microk8s
          ARGS: config
      - put: microk8s-config
        params:
          file: microk8s-config/ssh-exec.out

  - name: microk8s-clusterctl-init
    plan:
      - in_parallel:
          - get: pipelines
          - get: microk8s-config
            passed:
              - microk8s-config
          - get: clusterctl-release
            trigger: true
            params:
              glob: clusterctl-linux-amd64
      - task: clusterctl-init
        file: pipelines/tasks/clusterctl-init/task.yml
        input_mapping:
          clusterctl: clusterctl-release
          config: microk8s-config
        params:
          <<: *vsphere_env
          INFRASTRUCTURE: vsphere

  - name: gamboge-cluster-yaml
    plan:
      - in_parallel:
          - get: pipelines
            trigger: true
          - get: kube-template-info-v1.17.x
            trigger: true
            passed:
              - kube-templates-1.17.x
          - get: microk8s-config
            passed:
              - microk8s-clusterctl-init
          - get: clusterctl-release
            trigger: true
            params:
              glob: clusterctl-linux-amd64
      - task: generate-cluster-yaml
        file: pipelines/tasks/vsphere-cluster-config/task.yml
        input_mapping:
          clusterctl: clusterctl-release
          config: microk8s-config
        params:
          <<: *vsphere_env
          CLUSTER_NAME: gamboge
          VSPHERE_TEMPLATE: ubuntu-1804-kube-v1.17.5
          CONTROL_PLANE_ENDPOINT_IP: 192.168.77.60
          CONTROL_PLANE_MACHINE_COUNT: 3
          WORKER_MACHINE_COUNT: 1
          KUBERNETES_VERSION: 1.17.5
          NAMESPACE: default
          TEMPLATE_MEMORY: 32768
          TEMPLATE_DISK: 64
          TEMPLATE_CPU: 12
          TEMPLATE_SECONDARY_NETWORK: Storage Access
          CLUSTER_CIDR: 172.16.0.0/16
      - put: gamboge-cluster-yaml
        params:
          file: cluster/cluster.yaml

  - name: gamboge-cluster
    serial_groups:
      - cluster-creation
    on_failure:
      task: delete-cluster
      file: pipelines/tasks/kubectl-cmd/task.yml
      input_mapping:
        config: microk8s-config
      params:
        COMMAND: delete
        ARGS: cluster gamboge
    plan:
      - in_parallel:
          - get: pipelines
          - get: microk8s-config
            passed:
              - microk8s-clusterctl-init
          - get: gamboge-cluster-yaml
            trigger: true
            passed:
              - gamboge-cluster-yaml
      - task: create-cluster
        file: pipelines/tasks/kubectl-apply-template/task.yml
        input_mapping:
          config: microk8s-config
          templates: gamboge-cluster-yaml
      - task: wait-until-available
        file: pipelines/tasks/wait-until-cluster-available/task.yml
        input_mapping:
          config: microk8s-config
        params:
          NAME: gamboge
      - task: fetch-secret
        file: pipelines/tasks/kubectl-cmd/task.yml
        input_mapping:
          config: microk8s-config
        output_mapping:
          output: encoded-secret
        params:
          COMMAND: get
          ARGS: secret gamboge-kubeconfig -o jsonpath='{.data.value}'
      - task: decode-secret
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: encoded-secret
          outputs:
            - name: kubeconfig
          run:
            path: /bin/sh
            args:
              - -c
              - base64 -d encoded-secret/kubectl-cmd.out > kubeconfig/config
      - put: gamboge-kubeconfig
        params:
          file: kubeconfig/config

  - name: jonquil-cluster-yaml
    plan:
      - in_parallel:
          - get: pipelines
            trigger: true
          - get: kube-template-info-v1.18.x
            trigger: true
            passed:
              - kube-templates-1.18.x
          - get: microk8s-config
            passed:
              - microk8s-clusterctl-init
          - get: clusterctl-release
            trigger: true
            params:
              glob: clusterctl-linux-amd64
      - task: generate-cluster-yaml
        file: pipelines/tasks/vsphere-cluster-config/task.yml
        input_mapping:
          clusterctl: clusterctl-release
          config: microk8s-config
        params:
          <<: *vsphere_env
          CLUSTER_NAME: jonquil
          VSPHERE_TEMPLATE: ubuntu-1804-kube-v1.18.2
          CONTROL_PLANE_ENDPOINT_IP: 192.168.77.180
          CONTROL_PLANE_MACHINE_COUNT: 3
          WORKER_MACHINE_COUNT: 1
          KUBERNETES_VERSION: 1.18.2
          NAMESPACE: default
          TEMPLATE_MEMORY: 32768
          TEMPLATE_DISK: 64
          TEMPLATE_CPU: 12
          TEMPLATE_SECONDARY_NETWORK: Storage Access
          CLUSTER_CIDR: 172.17.0.0/16
      - put: jonquil-cluster-yaml
        params:
          file: cluster/cluster.yaml

  - name: jonquil-cluster
    serial_groups:
      - cluster-creation
    on_failure:
      task: delete-cluster
      file: pipelines/tasks/kubectl-cmd/task.yml
      input_mapping:
        config: microk8s-config
      params:
        COMMAND: delete
        ARGS: cluster jonquil
    plan:
      - in_parallel:
          - get: pipelines
          - get: microk8s-config
            passed:
              - microk8s-clusterctl-init
          - get: jonquil-cluster-yaml
            trigger: true
            passed:
              - jonquil-cluster-yaml
      - task: create-cluster
        file: pipelines/tasks/kubectl-apply-template/task.yml
        input_mapping:
          config: microk8s-config
          templates: jonquil-cluster-yaml
      - task: wait-until-available
        file: pipelines/tasks/wait-until-cluster-available/task.yml
        input_mapping:
          config: microk8s-config
        params:
          NAME: jonquil
      - task: fetch-secret
        file: pipelines/tasks/kubectl-cmd/task.yml
        input_mapping:
          config: microk8s-config
        output_mapping:
          output: encoded-secret
        params:
          COMMAND: get
          ARGS: secret jonquil-kubeconfig -o jsonpath='{.data.value}'
      - task: decode-secret
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: encoded-secret
          outputs:
            - name: kubeconfig
          run:
            path: /bin/sh
            args:
              - -c
              - base64 -d encoded-secret/kubectl-cmd.out > kubeconfig/config
      - put: jonquil-kubeconfig
        params:
          file: kubeconfig/config
