---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.18.0

params:
  DEBUG:
  KUBECONFIG: config/config
  TIMEOUT: 300
  ARGS:
  NEGATE:

inputs:
  - name: config
  - name: conditions
    optional: true

outputs:
  - name: output

run:
  path: /bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -x
      fi

      if [ -f "conditions/skip" ]; then
        echo "file: control/skip file exists, so skipping this task"
        exit 0
      fi

      ARG_ARRAY=(${ARGS})

      set +e
      LIST=$(kubectl get --no-headers "${ARG_ARRAY[@]}")
      set -e

      if [[ $NEGATE == true && "${LIST}" == "" ]]; then
        touch output/skip
      elif [[  "${LIST}" != "" ]]; then
        touch output/skip
      fi

      exit 0