---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mikefarah/yq
    tag: latest

inputs:
  - name: clusterctl
  - name: config

outputs:
  - name: cluster

params:
  KUBECONFIG: config/config
  NAMESPACE: default
  VSPHERE_PASSWORD:
  CLUSTER_NAME:
  CONTROL_PLANE_MACHINE_COUNT:
  WOKER_MACHINE_COUNT:
  KUBERNETES_VERSION:
  VSPHERE_DATACENTER:
  VSPHERE_DATASTORE:
  VSPHERE_FOLDER:
  VSPHERE_HAPROXY_TEMPLATE:
  VSPHERE_NETWORK:
  VSPHERE_RESOURCE_POOL:
  VSPHERE_SERVER:
  VSPHERE_SSH_AUTHORIZED_KEY:
  VSPHERE_TEMPLATE:
run:
  path: /bin/ash
  args:
    - -c
    - |
      set -e
      set -x

      chmod +x clusterctl/clusterctl-linux-amd64

      # ignore errors for the init, so things will continue if it has already
      # been initialized
      set +e
      clusterctl/clusterctl-linux-amd64 init --infrastructure vsphere
      set -e

      clusterctl/clusterctl-linux-amd64 config cluster gamboge > cluster/cluster.yaml

      echo '{"spec": {"template": {"spec": {"memoryMiB": 32768, "numCPUs": 12, "diskGiB": 64, "network": {"devices": [{"dhcp4": false, "networkName": "Storage Access"}]}}}}}' > template_patch.yaml
      yq merge -d3 -i -x -a cluster/cluster.yaml template_patch.yaml

      cat cluster/cluster.yaml