---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.18.0

params:
  DEBUG:
  KUBECONFIG: config/config
  IGNORE_ERROR:
  TIMEOUT: 300
  COMMAND:
  ARGS:

inputs:
  - name: config
  - name: conditions
    optional: true

outputs:
  - name: output

run:
  path: /bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -x
      fi

      if [ -f "conditions/skip" ]; then
        echo "file: control/skip file exists, so skipping this task"
      fi

      if [[ $IGNORE_ERROR == true ]]; then
        set +e
      else
        set -e
      fi

      ARG_ARRAY=(${ARGS})
      kubectl ${COMMAND} "${ARG_ARRAY[@]}" > output/kubectl-cmd.out

      exit 0