---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: in

outputs:
  - name: out

params:
  DECODE: true
  IN:
  OUT:

run:
  path: /bin/ash
  args:
    - -c
    - |

      if [[ "true" == "${DECODE}" ]]; then
        base64 -d "in/${IN}" > "out/${OUT}"
      else
        base64 "in/${IN}" > "out/${OUT}"
      fi
