---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/govc
    tag: latest

params:
  DEBUG:
  COMMAND:
  ARGS:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  IGNORE_ERROR:

inputs:
  - name: conditions
    optional: true
  - name: files
    optional: true

outputs:
  - name: output

run:
  path: /bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -x
        ls -lr files
      fi

      if [ -f "conditions/skip" ]; then
        echo "file: control/skip file exists, so skipping this task"
        exit 0
      fi

      if [[ $IGNORE_ERROR == true ]]; then
        set +e
      else
        set -e
      fi

      read -r -a ARGS <<< "$ARGS"
      govc $COMMAND "${ARGS[@]}" > output/govc-cmd.out

      exit 0