---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/govc
    tag: latest

params:
  DEBUG:
  ARGS:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  IGNORE_ERROR:

inputs:
  - name: files
    optional: true

run:
  path: /bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -x
        ls -lr files
      fi

      if [[ $IGNORE_ERROR == true ]]; then
        set +e
      else
        set -e
      fi

      read -r -a ARGS <<< "$ARGS"

      govc "${ARGS[@]}"

      exit 0