---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bitnami/kubectl
    tag: 1.19.2

params:
  DEBUG:
  IGNORE_ERROR:
  KUBECONFIG: config/config
  TIMEOUT: 300
  KIND:
  CLUSTER:
  NAMESPACED: true

inputs:
  - name: applications
  - name: config

run:
  path: /bin/bash
  args:
    - -c
    - |
      set -e

      if [[ $DEBUG == true ]]; then
        set -x
      fi

      # Only namespaces found in the apps repo will be pruned
      for PATH in applications/common/ns/*; do
        NAMESPACE=$(/usr/bin/basename $PATH)

        OBJECTS=()
        OBJECTS=($(/opt/bitnami/kubectl/bin/kubectl -n "$NAMESPACE" get "$KIND" -o custom-columns=NAME:.metadata.name --no-headers))

        for NAME in "${OBJECTS[@]}"; do
          if [ -n "$NAME" ]; then
            FILE="${NAMESPACE}/${NAME}-${KIND}.yaml"

            # Any resource of the specified kind, found that doesn't exist in the
            # common, or the cluster directories will be removed.
            if [[ ! (-f "applications/common/${FILE}" || -f "applications/${CLUSTER}/${FILE}") ]]; then
              echo "💀 Deleting $KIND: $NAMESPACE/$NAME"
              /opt/bitnami/kubectl/bin/kubectl -n "$NAMESPACE" delete "${KIND}" "${NAME}" --wait=true
            fi

          fi
        done

      done

      exit 0